### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by asbyth** [carbon-creature/carbon-creature.github.io#1]
![image](https://user-images.githubusercontent.com/36578995/133933927-df4adc05-1f8f-4048-8ffc-d51b998dca89.png)

**Comment by asbyth** [comment]
https://user-images.githubusercontent.com/36578995/133933954-8202980f-eaf7-4ca3-bfd8-275dcb0b48f8.mp4

**Comment by carbon-creature** [comment]
retarded

**Comment by carbon-creature** [comment]
i will fix this soon

**Comment by asbyth** [comment]
Sorry. my mistake
